pipeline {
    agent {
        docker {
            image 'mcr.microsoft.com/dotnet/core/sdk:3.1.101'
        }
    }
    stages {
        stage('Verify') {
            steps {
                powershell label: '', script: '''
                    dotnet --list-sdks
                    dotnet --list-runtimes
                '''
                powershell label: '', script: 'printenv'
                powershell label: '', script: 'ls -l "//C/Users/b/.jenkins/workspace/demo4-1/"'
            }
        }
        stage('Build') {
            steps {
                powershell label: '', script: 'dotnet build "$WORKSPACE/m4/src/Pi.Web/Pi.Web.csproj"'
            }
        }
        stage('Unit Test') {
            steps {
              dir("$WORKSPACE/m4/src") {
                powershell label: '', script: '''
                    dotnet test Pi.Math.Tests/Pi.Math.Tests.csproj
                    dotnet test Pi.Runtime.Tests/Pi.Runtime.Tests.csproj
                '''
              }
            }
        }
        stage('Smoke Test') {
            steps {
              powershell label: '', script: 'dotnet "$WORKSPACE/m4/src/Pi.Web/bin/Debug/netcoreapp3.1/Pi.Web.dll"'
            }
        }
    }
}