pipeline {
    agent {
        docker {
            image 'mcr.microsoft.com/dotnet/core/sdk:3.1.101'
        }
    }
    stages {
        stage('Verify') {
            steps {
                bat '''
                  dotnet --list-sdks
                  dotnet --list-runtimes
                '''
                bat 'printenv'
                bat 'ls -l "$WORKSPACE"'
            }
        }
        stage('Build') {
            steps {
                bat 'dotnet build "$WORKSPACE/m4/src/Pi.Web/Pi.Web.csproj"'
            }
        }
        stage('Unit Test') {
            steps {
              dir("$WORKSPACE/m4/src") {
                bat '''
                    dotnet test Pi.Math.Tests/Pi.Math.Tests.csproj
                    dotnet test Pi.Runtime.Tests/Pi.Runtime.Tests.csproj
                '''
              }
            }
        }
        stage('Smoke Test') {
            steps {
              bat 'dotnet "$WORKSPACE/m4/src/Pi.Web/bin/Debug/netcoreapp3.1/Pi.Web.dll"'
            }
        }
    }
}